joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
whole_body_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_lift_joint
    - arm_flex_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
